/**
 * write-registry/dsl.ts — the declaration language of the write registry (AI_MIMARI_V2 §4.1).
 *
 * One `op()` per writable thing declares: when it is (and is NOT) a record, its typed fields with
 * units/ranges/enum meanings, the arithmetic code may do (`derive`), and the rules that turn a
 * model decision into COMMIT | FLAG | ASK | REJECT (§5). Everything else is GENERATED from these
 * declarations: the strict json_schema the model decodes against, the Turkish doc it reads, the
 * validator, the receipts. Change a field here and all four move together — that is the point.
 *
 * Hand-rolled, zero dependencies, no Deno APIs: the generated bytes must be ours to keep stable
 * (prompt-cache prefix, registry.test.ts byte snapshot).
 */
import type { RefKind, RefTarget, RenderedRefs } from './refs.ts';

// ─── Field specs ─────────────────────────────────────────────────────────────

interface SpecBase {
  /** Turkish meaning shown to the model (schema description + doc). */
  readonly tr?: string;
}

export interface NumSpec<N extends boolean = boolean> extends SpecBase {
  readonly kind: 'num';
  readonly nullable: N;
  readonly unit?: string;
  /** Physically impossible outside this → REJECT. */
  readonly hard?: readonly [number, number];
  /** Possible but unusual outside this → ASK. */
  readonly plausible?: readonly [number, number];
  /** Column precision: a finer value is rounded and listed in `normalized[]` (lossless, visible). */
  readonly decimals?: number;
}

export interface TextSpec<N extends boolean = boolean> extends SpecBase {
  readonly kind: 'text';
  readonly nullable: N;
  /** Soft cap: longer text is kept as-is and FLAGged (never truncated silently). */
  readonly max?: number;
  /** 'hhmm' = 24-hour HH:MM the model converts to; anything else → ASK, never dropped. */
  readonly format?: 'hhmm';
}

export interface BoolSpec<N extends boolean = boolean> extends SpecBase {
  readonly kind: 'bool';
  readonly nullable: N;
}

export interface EnumSpec<K extends string = string, N extends boolean = boolean> extends SpecBase {
  readonly kind: 'enum';
  readonly nullable: N;
  /** id → Turkish meaning. Ids are stored; meanings are what the model reads. */
  readonly values: Readonly<Record<K, string>>;
}

export interface EnumListSpec<K extends string = string> extends SpecBase {
  readonly kind: 'enumList';
  readonly values: Readonly<Record<K, string>>;
  readonly max?: number;
}

export interface TextListSpec extends SpecBase {
  readonly kind: 'textList';
  readonly max?: number;
}

/** A log day: 'today' | 'yesterday' | 'YYYY-MM-DD'; never future, at most MAX_BACK_DAYS back. */
export interface DaySpec<N extends boolean = boolean> extends SpecBase {
  readonly kind: 'day';
  readonly nullable: N;
}

/** An ISO date with an explicit window (life events are in the future, lab results in the past). */
export interface DateSpec<N extends boolean = boolean> extends SpecBase {
  readonly kind: 'date';
  readonly nullable: N;
  readonly past_days?: number;
  readonly future_days?: number;
}

export interface RefSpec<N extends boolean = boolean> extends SpecBase {
  readonly kind: 'ref';
  readonly nullable: N;
  readonly kinds: readonly RefKind[];
  /** For d#/t# refs: which record types are acceptable (water_log.replaces → water only). */
  readonly targets?: readonly RefTarget[];
}

export interface ListSpec<F extends Fields = Fields> extends SpecBase {
  readonly kind: 'list';
  readonly min: number;
  readonly max: number;
  readonly fields: F;
}

export interface ObjSpec<F extends Fields = Fields, N extends boolean = boolean> extends SpecBase {
  readonly kind: 'obj';
  readonly nullable: N;
  readonly fields: F;
}

/** record_ops.update.patch — "the same shape as a write" (one `$defs` entry, never a copy). */
export interface WriteSpec extends SpecBase {
  readonly kind: 'write';
}

export type FieldSpec =
  | NumSpec | TextSpec | BoolSpec | EnumSpec | EnumListSpec | TextListSpec
  | DaySpec | DateSpec | RefSpec | ListSpec | ObjSpec | WriteSpec;

export type Fields = { readonly [name: string]: FieldSpec };

// ─── Type inference: the model's args, typed from the declaration ────────────

type Nul<N, T> = N extends true ? T | null : T;

/** A write as the model emits it (validated shape; op-specific typing lives in each op file). */
export type WriteCall = { op: string } & Record<string, unknown>;

export type ValueOf<S> =
  S extends NumSpec<infer N> ? Nul<N, number>
  : S extends TextSpec<infer N> ? Nul<N, string>
  : S extends BoolSpec<infer N> ? Nul<N, boolean>
  : S extends EnumSpec<infer K, infer N> ? Nul<N, K>
  : S extends EnumListSpec<infer K> ? K[]
  : S extends TextListSpec ? string[]
  : S extends DaySpec<infer N> ? Nul<N, string>
  : S extends DateSpec<infer N> ? Nul<N, string>
  : S extends RefSpec<infer N> ? Nul<N, string>
  : S extends ListSpec<infer F> ? Array<Infer<F>>
  : S extends ObjSpec<infer F, infer N> ? Nul<N, Infer<F>>
  : S extends WriteSpec ? WriteCall
  : never;

export type Infer<F extends Fields> = { -readonly [K in keyof F]: ValueOf<F[K]> };

// ─── Builders ────────────────────────────────────────────────────────────────

type NullOf<O> = O extends { nullable: true } ? true : false;

interface NumOpts { nullable?: boolean; unit?: string; hard?: readonly [number, number]; plausible?: readonly [number, number]; decimals?: number; tr?: string }
interface TextOpts { nullable?: boolean; max?: number; format?: 'hhmm'; tr?: string }
interface PlainOpts { nullable?: boolean; tr?: string }
interface DateOpts { nullable?: boolean; past_days?: number; future_days?: number; tr?: string }
interface RefOpts { nullable?: boolean; targets?: readonly RefTarget[]; tr?: string }

function withNull<O extends { nullable?: boolean }, T extends object>(o: O | undefined, spec: T): T & { nullable: NullOf<O> } {
  return { ...spec, ...(o ?? {}), nullable: (o?.nullable === true) as NullOf<O> };
}

export const f = {
  num: <O extends NumOpts>(o?: O): NumSpec<NullOf<O>> => withNull(o, { kind: 'num' as const }),
  text: <O extends TextOpts>(o?: O): TextSpec<NullOf<O>> => withNull(o, { kind: 'text' as const }),
  bool: <O extends PlainOpts>(o?: O): BoolSpec<NullOf<O>> => withNull(o, { kind: 'bool' as const }),
  enum: <K extends string, O extends PlainOpts>(values: Readonly<Record<K, string>>, o?: O): EnumSpec<K, NullOf<O>> =>
    withNull(o, { kind: 'enum' as const, values }),
  enumList: <K extends string>(values: Readonly<Record<K, string>>, o?: { max?: number; tr?: string }): EnumListSpec<K> =>
    ({ kind: 'enumList', values, ...(o ?? {}) }),
  textList: (o?: { max?: number; tr?: string }): TextListSpec => ({ kind: 'textList', ...(o ?? {}) }),
  day: <O extends PlainOpts>(o?: O): DaySpec<NullOf<O>> => withNull(o, { kind: 'day' as const }),
  date: <O extends DateOpts>(o?: O): DateSpec<NullOf<O>> => withNull(o, { kind: 'date' as const }),
  ref: <O extends RefOpts>(kinds: readonly RefKind[], o?: O): RefSpec<NullOf<O>> => withNull(o, { kind: 'ref' as const, kinds }),
  list: <F extends Fields>(o: { min: number; max: number; tr?: string }, fields: F): ListSpec<F> => ({ kind: 'list', ...o, fields }),
  obj: <F extends Fields, O extends PlainOpts>(fields: F, o?: O): ObjSpec<F, NullOf<O>> => withNull(o, { kind: 'obj' as const, fields }),
  write: (o?: { tr?: string }): WriteSpec => ({ kind: 'write', ...(o ?? {}) }),
};

// ─── Validation context (pure data; the caller loads it) ─────────────────────

/** ED tier (shared/safety-state.ts EDTier) + 'unknown' = the read failed → fail closed (§7.1). */
export type EdTier = 'none' | 'watch' | 'amber' | 'red' | 'unknown';

/** Per-day totals already stored, before this turn's writes. */
export interface DayTotals {
  water_liters?: number | null;
  steps?: number | null;
  sleep_hours?: number | null;
  weight_kg?: number | null;
}

/** One REFERANS ADAYLARI row shown to the model this turn (a hint; code never picks it). */
export interface ReferenceRow {
  key: string;
  name_tr: string;
  kcal_per_100g: number;
  protein_per_100g?: number | null;
  carbs_per_100g?: number | null;
  fat_per_100g?: number | null;
}

export interface ValidationContext {
  /** The user's effective local day, YYYY-MM-DD. */
  today: string;
  /** Wall clock for hold expiry checks (ISO). */
  now_iso: string;
  /** The raw user message — read ONLY by the verbatim evidence-quote check (§5 exception). */
  user_message: string;
  /** Exactly the refs rendered to the model this turn. Anything else is rejected. */
  refs: RenderedRefs;
  day_totals?: Readonly<Record<string, DayTotals>>;
  /** Stored identity/targets, for materiality checks (§5.1.7). */
  profile?: {
    birth_year?: number | null;
    height_cm?: number | null;
    weight_kg?: number | null;
    gender?: string | null;
    periodic_state?: string | null;
  } | null;
  /** Latest stored weigh-in within the last 14 days (jump plausibility). */
  last_weight?: { kg: number; day: string } | null;
  goal?: { goal_type: string | null; target_weight_kg: number | null } | null;
  ed_tier: EdTier;
  reference_rows?: Readonly<Record<string, ReferenceRow>>;
}

/** How many days back a log may be dated (§5.1.3). */
export const MAX_BACK_DAYS = 7;

// ─── Rules and issues ────────────────────────────────────────────────────────

export type IssueLevel = 'hard' | 'ask' | 'flag';

/** One reason, visible to the model (Stage B fact) and the user (receipt / question). */
export interface Issue {
  code: string;
  level: IssueLevel;
  /** Why, in Turkish with diacritics. */
  tr: string;
  /** Field path inside the write ('items[0].kcal'). */
  path?: string;
  /** REJECT only: the model can fix it with what it already knows → one repair call. */
  repairable?: boolean;
  /** REJECT only: receipt failure_class (client red badge). */
  failure_class?: string;
  /** ASK only: the single question Stage B should ask, in its own words. */
  question_tr?: string;
}

export interface RuleDef<A, D> {
  code: string;
  /** What the rule means, for the generated doc ("tek seferde 1,5 L üstü"). */
  doc_tr: string;
  /** Truthy = violated. A string replaces doc_tr as the issue text (to quote numbers). */
  test(a: A, d: D, ctx: ValidationContext): boolean | string | null | undefined;
  path?: string;
  repairable?: boolean;
  failure_class?: string;
  question_tr?: string;
}

export function rule<A, D>(
  code: string,
  doc_tr: string,
  test: (a: A, d: D, ctx: ValidationContext) => boolean | string | null | undefined,
  extra?: { path?: string; repairable?: boolean; failure_class?: string; question_tr?: string },
): RuleDef<A, D> {
  return { code, doc_tr, test, ...(extra ?? {}) };
}

// ─── op() ────────────────────────────────────────────────────────────────────

/** Which array of the understanding envelope an op belongs to. */
export type Channel = 'writes' | 'record_ops' | 'pending_ops' | 'commitment_ops' | 'memory';

export type UndoMode = 'soft_delete' | 'restore_previous' | 'deactivate' | 'supersede' | 'resolve' | 'none';

export interface WritesDecl {
  /** Phase-1 writer RPC (atomic, writes turn_writes in the same transaction). */
  rpc?: string;
  /** Shared-module writer when the write is not a single RPC (syncConstraint…). */
  fn?: string;
  tables: readonly string[];
  undo: UndoMode;
  /** pending_writes.op when the write is held (ASK). */
  hold_op?: string;
}

export interface OpDef<F extends Fields, D extends object> {
  /** Registry id, unique across channels (also the turn_writes.op / pending_writes.op name). */
  type: string;
  /** Wire discriminator inside the channel ('delete' in record_ops). Defaults to `type`. */
  op?: string;
  channel: Channel;
  /** Legacy envelope action type, so the client's BADGE_DEFS keep working (§4.1). */
  envelope: string | ((a: Infer<F>) => string);
  title_tr: string;
  when_tr: string;
  not_when_tr?: string;
  fields: F;
  derive?: (a: Infer<F>, ctx: ValidationContext) => D;
  /** "Kod ne hesaplar" — doc line for derive(). */
  derive_tr?: string;
  /** Doc line: the two-step (hold) policy, when there is one. */
  hold_tr?: string;
  /** Each element of this list field is its own atomic write (profile_set.changes). */
  atomic_list?: keyof F & string;
  /**
   * The model DECLARED this write as nothing to store (meal status=restatement). Valid, not an
   * error, no receipt — and visible in the verdict, so a shadow diff can see it.
   */
  noop?: (a: Infer<F>) => string | false | null;
  writes: WritesDecl;
  invariants?: readonly string[];
  /** Short Turkish examples for the doc ("1 bardak su daha" → …). */
  examples_tr?: readonly string[];
  /** Extra doc lines the field table cannot express (profile_set's per-field contracts). */
  doc_appendix_tr?: readonly string[];
  /** The coach-facing line in capabilities.ts (defaults to the first sentence of when_tr). */
  capability_tr?: string;
}

/** Rule metadata the generators read (no functions needed for docs). */
export interface RuleDoc {
  code: string;
  doc_tr: string;
}

/** The type-erased op the registry stores. Each op's typed rules live in its closure. */
export interface RegOp {
  readonly type: string;
  readonly op: string;
  readonly channel: Channel;
  readonly title_tr: string;
  readonly when_tr: string;
  readonly not_when_tr?: string;
  readonly fields: Fields;
  readonly derive_tr?: string;
  readonly hold_tr?: string;
  readonly rule_docs: { readonly hard: readonly RuleDoc[]; readonly ask: readonly RuleDoc[]; readonly flag: readonly RuleDoc[] };
  readonly atomic_list?: string;
  readonly writes: WritesDecl;
  readonly invariants: readonly string[];
  readonly examples_tr: readonly string[];
  readonly doc_appendix_tr: readonly string[];
  readonly capability_tr?: string;
  /** Legacy envelope type for these args. */
  envelopeFor(args: Record<string, unknown>): string;
  /**
   * derive() + the op's own rules. Callers MUST run the structural field checks first and call
   * this only when they found no hard structural error (the args then match the declared types).
   */
  evaluate(args: Record<string, unknown>, ctx: ValidationContext): { derived: Record<string, unknown>; issues: Issue[]; noop: string | null };
}

function toDocs<A, D>(rs: ReadonlyArray<RuleDef<A, D>> | undefined): RuleDoc[] {
  return (rs ?? []).map((r) => ({ code: r.code, doc_tr: r.doc_tr }));
}

/**
 * The op's rules, by outcome: hard → REJECT, ask → ASK (hold), flag → FLAG (store + note).
 * Given in a second step (`op({...}).rules({...})`) so every rule is typed against the op's
 * already-inferred args and derive() output.
 */
export interface RuleSet<A, D> {
  hard?: ReadonlyArray<RuleDef<A, D>>;
  ask?: ReadonlyArray<RuleDef<A, D>>;
  flag?: ReadonlyArray<RuleDef<A, D>>;
}

/** An op without rules yet; `.rules()` returns the final op. Usable as a RegOp as-is. */
export interface OpBuilder<F extends Fields, D extends object> extends RegOp {
  rules(r: RuleSet<Infer<F>, D>): RegOp;
}

export function op<F extends Fields, D extends object = Record<string, never>>(def: OpDef<F, D>): OpBuilder<F, D> {
  const build = (r: RuleSet<Infer<F>, D>): RegOp => buildOp(def, r);
  return { ...build({}), rules: build };
}

function buildOp<F extends Fields, D extends object>(def: OpDef<F, D>, rs: RuleSet<Infer<F>, D>): RegOp {
  const run = (level: IssueLevel, rs: ReadonlyArray<RuleDef<Infer<F>, D>> | undefined, a: Infer<F>, d: D, ctx: ValidationContext, out: Issue[]) => {
    for (const r of rs ?? []) {
      const hit = r.test(a, d, ctx);
      if (!hit) continue;
      out.push({
        code: r.code,
        level,
        tr: typeof hit === 'string' ? hit : r.doc_tr,
        ...(r.path ? { path: r.path } : {}),
        ...(level === 'hard' ? { repairable: r.repairable === true, failure_class: r.failure_class ?? 'invalid_value' } : {}),
        ...(level === 'ask' && r.question_tr ? { question_tr: r.question_tr } : {}),
      });
    }
  };
  return {
    type: def.type,
    op: def.op ?? def.type,
    channel: def.channel,
    title_tr: def.title_tr,
    when_tr: def.when_tr,
    not_when_tr: def.not_when_tr,
    fields: def.fields,
    derive_tr: def.derive_tr,
    hold_tr: def.hold_tr,
    rule_docs: { hard: toDocs(rs.hard), ask: toDocs(rs.ask), flag: toDocs(rs.flag) },
    atomic_list: def.atomic_list,
    writes: def.writes,
    invariants: def.invariants ?? [],
    examples_tr: def.examples_tr ?? [],
    doc_appendix_tr: def.doc_appendix_tr ?? [],
    capability_tr: def.capability_tr,
    envelopeFor(args) {
      return typeof def.envelope === 'string' ? def.envelope : def.envelope(args as Infer<F>);
    },
    evaluate(args, ctx) {
      // Safe by contract: the structural pass already proved `args` matches `fields`.
      const a = args as Infer<F>;
      const d = (def.derive ? def.derive(a, ctx) : {}) as D;
      const issues: Issue[] = [];
      run('hard', rs.hard, a, d, ctx, issues);
      run('ask', rs.ask, a, d, ctx, issues);
      run('flag', rs.flag, a, d, ctx, issues);
      return { derived: d as Record<string, unknown>, issues, noop: (def.noop && def.noop(a)) || null };
    },
  };
}
